<?php
session_start();

/*Restart Checkup if user clicks restart button*/

if ($_SERVER["QUERY_STRING"]=="restart") {
  $_SESSION["group"]="";
}

/*Make sure session lasts 30 minutes*/

if (isset($_SESSION['LAST_ACTIVITY']) && (time() - $_SESSION['LAST_ACTIVITY'] > 1800)) {
    // last request was more than 30 minutes ago
    session_unset();
    session_destroy();
}
$_SESSION['LAST_ACTIVITY'] = time();


/*Include functions*/

require_once '/checkup/functions.php';

?>
<link rel="stylesheet" href="/checkup/checkup.css" type="text/css" />
<script type="text/javascript" language="javascript" src="/checkup/checkup.js"></script>
<script type="text/javascript" language="javascript" src="/checkup/jquery.js"></script>
<?php

/*If user clicked start set the group variable to 1*/

if ($_SERVER["QUERY_STRING"]=="checkup") {
  $_SESSION["group"]="1";
}

/*Start of the Checkup*/

if ($_SESSION["group"]!="") {
  echo "<a class=\"btn\" style=\"float:right;margin-left:10px;\" href=\"/estate-planning-checkup/?restart\">Restart Checkup</a>";
}

if ($_SESSION["group"]=="1") {

  if ($_POST["group1"]=="Continue") {

    /*Check Answers to Preliminary Questions*/

    $_SESSION["group"]="2";

    $state=$_POST["state"];
    $_SESSION["state"]=$state;
    if ($state=="North Carolina") {
      $statemsg="<div class=\"msg\">If you live in the State of North Carolina you cannot use the estate planning documents generated by this website.</div>";
      $_SESSION["group"]="1";
    }

    if ($_POST["foreign"]=="on") {
      $foreign=true;
    }
    else {
      $foreign=false;
      $foreignmsg="<div class=\"msg\">If your property is in a foreign country the estate planning documents generated by this website are not appropriate for you.</div>";
      $_SESSION["group"]="1";
    }

    if ($_POST["disputed"]=="on") {
      $disputed=true;
    }
    else {
      $disputed=false;
      $disputedmsg="<div class=\"msg\">If you think your Will is going to be contested in court by someone you should not use the Will generated at this website.</div>";
      $_SESSION["group"]="1";
    }

    if ($_POST["value"]=="on") {
      $value=true;
    }
    else {
      $value=false;
      $valuemsg="<div class=\"msg\">If your assets are more than &#36;5.3 million you will want to use a Will that is designed to minimize federal and state inheritance and estate taxes.</div>";
      $_SESSION["group"]="1";
    }

  }
  if ($_SESSION["group"]=="1") {
    /*Preliminary Questions*/
    echo "<h2>Preliminary Questions</h2>\n";
    echo "<form onclick=\"toggle('edit',event)\" method=\"post\" action=\"/estate-planning-checkup/\">\n";
    echo $statemsg;
    stateselect($state);
    echo $foreignmsg;
    check("foreign","None of the property which will be named in this Will is located in a foreign country.",$foreign,"If your property is in a foreign country the estate planning documents generated by this website are not appropriate for you.");
    echo $disputedmsg;
    check("disputed","I have no reason to believe that this Will shall be contested or disputed by anyone.",$disputed,"If you think your Will is going to be contested in court by someone you should not use the Will generated at this website.");
    echo $valuemsg;
    check("value","The total value of my estate (all property and assets) is less than the &#36;5.3 million federal estate tax limit.",$value,"If your assets are more than &#36;5.3 million you will want to use a Will that is designed to minimize federal and state inheritance and estate taxes.");
    echo "<input class=\"btn\" type=\"submit\" name=\"group1\" value=\"Continue\" />\n";
    echo "</form>\n";

    /*If form has been submitted but user could not proceed show attorney recommendation*/
    if ($_POST["group1"]=="Continue") {
      echo "<div class=\"conclusion\"><h2>Conclusion</h2><p>You must answer YES to all the questions above to use the Estate Planning Documents generated by this website. The forms generated by this website are not suitable if you are under 18 or live outside of the United States or its territories, have complex family circumstances or a large or complicated estate.  If your estate exceeds the estate tax threshold of &#36;5.3 million, or if you own a business or agricultural property, or you share ownership of a property, or you own property outside of the United States, we recommend that you seek the advice of an attorney.</p>";
      echo "<p><b>Find a lawyer in your state who provides fixed-fee online service.<br />";
      echo "<a class=\"btn\" href=\"/online-lawyers/\">Click to Start</a></p></div>";
    }
  }
}
if ($_SESSION["group"]=="2") {

  if ($_POST["group2"]=="Continue") {

    /*Check Answers to Group 2 Questions*/

    $_SESSION["group"]="3";

    if ($_POST["mf"]=="m") {
      $mf="m";
    }
    else if ($_POST["mf"]=="f") {
      $mf="f";
    }
    else {
      $mfmsg="<div class=\"msg\">Please select male or female.</div>";
      $_SESSION["group"]="2";
    }

    if ($_POST["marital"]=="married") {
      $marital="married";
      $_SESSION["married"]="married";
    }
    else if ($_POST["marital"]=="single") {
      $marital="single";
      $_SESSION["married"]="no";
    }
    else if ($_POST["marital"]=="divorced") {
      $marital="divorced";
      $_SESSION["married"]="no";
    }
    else if ($_POST["marital"]=="engaged") {
      $marital="engaged";
      $_SESSION["married"]="engaged";
    }
    else if ($_POST["marital"]=="widowed") {
      $marital="widowed";
      $_SESSION["married"]="no";
    }
    else if ($_POST["marital"]=="dp") {
      $marital="dp";
      $_SESSION["married"]="no";
    }
    else {
      $maritalmsg="<div class=\"msg\">Please select your marital status.</div>";
      $_SESSION["group"]="2";
    }
    if ($_POST["children"]=="yes") {
      $children="yes";
      $_SESSION["children"]="yes";
      if ($_POST["children18"]=="yes") {
        $children18="yes";
      }
      else if ($_POST["children18"]=="no") {
        $children18="no";
      }
      else {
        $children18msg="<div class=\"msg\">Please select whether any of your children are under 18.</div>";
        $_SESSION["group"]="2";
      }
    }
    else if ($_POST["children"]=="plan") {
      $_SESSION["children"]="plan";
      $children="plan";
    }
    else if ($_POST["children"]=="noplan") {
      $_SESSION["children"]="no";
      $children="noplan";
    }
    else if ($_POST["children"]=="undecided") {
      $_SESSION["children"]="undecided";
      $children="undecided";
    }
    else {
      $childrenmsg="<div class=\"msg\">Please select whether you have children.</div>";
      $_SESSION["group"]="2";
    }
    if ($_POST["house"]=="on") {
      $house=true;
    }
    else {
      $house=false;
    }
    if ($_POST["car"]=="on") {
      $car=true;
    }
    else {
      $car=false;
    }
    if ($_POST["other"]=="on") {
      $other=true;
    }
    else {
      $other=false;
    }
    if ($_POST["savings"]=="yes") {
      $savings="yes";
    }
    else if ($_POST["savings"]=="no") {
      $savings="no";
    }
    else {
      $savingsmsg="<div class=\"msg\">Please select whether you have investments or savings.</div>";
      $_SESSION["group"]="2";
    }
    if ($_POST["charity"]=="yes") {
      $charity="yes";
    }
    else if ($_POST["charity"]=="no") {
      $charity="no";
    }
    else if ($_POST["charity"]=="undecided") {
      $charity="undecided";
    }
    else {
      $charitymsg="<div class=\"msg\">Please select whether you plan to leave money or property to charity.</div>";
      $_SESSION["group"]="2";
    }
  }
  if ($_SESSION["group"]=="2") {
    /*Will Questions*/
    echo "<h2>Will Questions</h2>\n";
    echo "<form onclick=\"toggle('edit',event)\" method=\"post\" action=\"/estate-planning-checkup/\">\n";
    echo $mfmsg;
    echo "<label for=\"mf\">Are you male or female?</label><br /><select id=\"mf\" name=\"mf\">\n";
    echo "<option value=\"--\"> -- Please Select -- </option>\n";
    if ($mf=="m") {
      echo "<option selected=\"selected\" value=\"m\">Male</option>\n";
    }
    else {
      echo "<option value=\"m\">Male</option>\n";
    }
    if ($mf=="f") {
      echo "<option selected=\"selected\" value=\"f\">Female</option>\n";
    }
    else {
      echo "<option value=\"f\">Female</option>\n";
    }
    echo "</select><br />\n";
    echo $maritalmsg;
    echo "<label for=\"marital\">What is your marital status?</label><br /><select id=\"marital\" name=\"marital\">\n";
    echo "<option value=\"--\"> -- Please Select -- </option>\n";
    if ($marital=="married") {
      echo "<option selected=\"selected\" value=\"married\">Married</option>\n";
    }
    else {
      echo "<option value=\"married\">Married</option>\n";
    }
    if ($marital=="single") {
      echo "<option selected=\"selected\" value=\"single\">Single</option>\n";
    }
    else {
      echo "<option value=\"single\">Single</option>\n";
    }
    if ($marital=="divorced") {
      echo "<option selected=\"selected\" value=\"divorced\">Divorced</option>\n";
    }
    else {
      echo "<option value=\"divorced\">Divorced</option>\n";
    }
    if ($marital=="enngaged") {
      echo "<option selected=\"selected\" value=\"enngaged\">Engaged</option>\n";
    }
    else {
      echo "<option value=\"engaged\">Engaged</option>\n";
    }
    if ($marital=="widowed") {
      echo "<option selected=\"selected\" value=\"widowed\">Widowed</option>\n";
    }
    else {
      echo "<option value=\"widowed\">Widowed</option>\n";
    }
    if ($marital=="dp") {
      echo "<option selected=\"selected\" value=\"dp\">In a Domestic/Civil Partnership</option>\n";
    }
    else {
      echo "<option value=\"dp\">In a Domestic/Civil Partnership</option>\n";
    }
    echo "</select><br />\n";
    echo $childrenmsg;
    echo "<label for=\"children\">Do you have children?</label><br /><select id=\"children\" name=\"children\" onchange=\"vis18();\">\n";
    echo "<option value=\"--\"> -- Please Select -- </option>\n";
    if ($children=="yes") {
      echo "<option selected=\"selected\" value=\"yes\">Yes, I have children.</option>\n";
    }
    else {
      echo "<option value=\"yes\">Yes, I have children.</option>\n";
    }
    if ($children=="plan") {
      echo "<option selected=\"selected\" value=\"plan\">No, but I plan to have children.</option>\n";
    }
    else {
      echo "<option value=\"plan\">No, but I plan to have children.</option>\n";
    }
    if ($children=="noplan") {
      echo "<option selected=\"selected\" value=\"noplan\">No, and I don't plan on having children.</option>\n";
    }
    else {
      echo "<option value=\"noplan\">No, and I don't plan on having children.</option>\n";
    }
    if ($children=="undecided") {
      echo "<option selected=\"selected\" value=\"undecided\">No, and I haven't decided whether I want children.</option>\n";
    }
    else {
      echo "<option value=\"undecided\">No, and I haven't decided whether I want children.</option>\n";
    }
    echo "</select><br />\n";
    if ($children=="yes") {
      echo "<div id=\"children18div\">\n";
    }
    else {
      echo "<div style=\"display:none;\" id=\"children18div\">\n";
    }
    echo $children18msg;
    echo "<label for=\"children18\">Are any of your children under 18 years old?</label><br /><select id=\"children18\" name=\"children18\">\n";
    echo "<option value=\"--\"> -- Please Select -- </option>\n";
    if ($children18=="yes") {
      echo "<option selected=\"selected\" value=\"yes\">Yes</option>\n";
    }
    else {
      echo "<option value=\"yes\">Yes</option>\n";
    }
    if ($children18=="no") {
      echo "<option selected=\"selected\" value=\"no\">No</option>\n";
    }
    else {
      echo "<option value=\"no\">No</option>\n";
    }
    echo "</select></div>\n";
    echo "<b>Property</b><br />\n";
    check("house","I own a house.",$house,"");
    check("car","I own a car.",$car,"");
    check("other","I own other kinds of property.",$other,"");
    echo $savingsmsg;
    echo "<label for=\"savings\">Do you have investments or savings?</label><br /><select id=\"savings\" name=\"savings\">\n";
    echo "<option value=\"--\"> -- Please Select -- </option>\n";
    if ($savings=="yes") {
      echo "<option selected=\"selected\" value=\"yes\">Yes, I have a retirement account, savings, or other types of investment.</option>\n";
    }
    else {
      echo "<option value=\"yes\">Yes, I have a retirement account, savings, or other types of investment.</option>\n";
    }
    if ($savings=="no") {
      echo "<option selected=\"selected\" value=\"no\">No, I don't have any investments or savings.</option>\n";
    }
    else {
      echo "<option value=\"no\">No, I don't have any investments or savings.</option>\n";
    }
    echo "</select>\n";
    tt("investments","Investments include pensions, 401Ks, stock holdings, bonds, etc.");
    echo "<br />";
    echo $charitymsg;
    echo "<label for=\"charity\">Do you want to leave any money or property to charity?</label><br /><select id=\"charity\" name=\"charity\">\n";
    echo "<option value=\"--\"> -- Please Select -- </option>\n";
    if ($charity=="yes") {
      echo "<option selected=\"selected\" value=\"yes\">Yes.</option>\n";
    }
    else {
      echo "<option value=\"yes\">Yes</option>\n";
    }
    if ($charity=="no") {
      echo "<option selected=\"selected\" value=\"no\">No.</option>\n";
    }
    else {
      echo "<option value=\"no\">No</option>\n";
    }
    if ($charity=="undecided") {
      echo "<option selected=\"selected\" value=\"undecided\">I haven't decided.</option>\n";
    }
    else {
      echo "<option value=\"undecided\">I haven't decided.</option>\n";
    }
    echo "</select>\n";
    echo "<br /><input class=\"btn\" type=\"submit\" name=\"group2\" value=\"Continue\" />\n";
    echo "</form>\n";
  }
}

if ($_SESSION["group"]=="3") {

  if ($_POST["group3"]=="Continue") {

    /*Check Answers to Group 3 Question*/

    $_SESSION["group"]="4";

    if ($_POST["hc"]=="yes") {
      $hc="yes";
      $_SESSION["hc"]="hc";
    }
    else if ($_POST["hc"]=="no") {
      $hc="no";
      $_SESSION["hc"]="no";
    }
    else {
      $hcmsg="<div class=\"msg\">Please select whether you want to name someone to make healthcare decisions for you if you can't.</div>";
      $_SESSION["group"]="3";
    }
  }
  if ($_SESSION["group"]=="3") {
    /*Healthcare Power of Attorney Question*/
    echo "<h2>Healthcare Power of Attorney Question</h2>\n";
    echo "<form onclick=\"toggle('edit',event)\" method=\"post\" action=\"/estate-planning-checkup/\">\n";
    echo $hcmsg;
    echo "<label for=\"hc\">Do you want to name someone to make healthcare decisions for you if you can't?</label><br /><select id=\"hc\" name=\"hc\">\n";
    echo "<option value=\"--\"> -- Please Select -- </option>\n";
    if ($hc=="yes") {
      echo "<option selected=\"selected\" value=\"yes\">Yes, I want to name someone to make healthcare decisions on my behalf.</option>\n";
    }
    else {
      echo "<option value=\"yes\">Yes, I want to name someone to make healthcare decisions on my behalf.</option>\n";
    }
    if ($hc=="no") {
      echo "<option selected=\"selected\" value=\"no\">No, I do not  want to name someone to make healthcare decisions on my behalf.</option>\n";
    }
    else {
      echo "<option value=\"no\">No, I do not  want to name someone to make healthcare decisions on my behalf.</option>\n";
    }
    echo "</select>\n";
    tt("healthcare","The person who is appointed to make the decisions will make them based on the directions in your document.");
    echo "<br /><input class=\"btn\" type=\"submit\" name=\"group3\" value=\"Continue\" />\n";
    echo "</form>\n";
  }
}
if ($_SESSION["group"]=="4") {

  if ($_POST["group4"]=="Continue") {

    /*Check Answers to Group 4 Question*/

    $_SESSION["group"]="5";

    if ($_POST["fp"]=="yes") {
      $fp="yes";
      $_SESSION["fp"]="fp";
    }
    else if ($_POST["fp"]=="no") {
      $fp="no";
      $_SESSION["fp"]="no";
    }
    else {
      $fpmsg="<div class=\"msg\">Please select whether you want to name someone to make legal or financial decisions for you if you can't.</div>";
      $_SESSION["group"]="4";
    }
  }
  if ($_SESSION["group"]=="4") {
    /*Financial Power of Attorney Question*/
    echo "<h2>Financial Power of Attorney Question</h2>\n";
    echo "<form onclick=\"toggle('edit',event)\" method=\"post\" action=\"/estate-planning-checkup/\">\n";
    echo $fpmsg;
    echo "<label for=\"fp\">Do you want to name someone to make legal or financial decisions for you if you can't?</label><br /><select id=\"fp\" name=\"fp\">\n";
    echo "<option value=\"--\"> -- Please Select -- </option>\n";
    if ($fp=="yes") {
      echo "<option selected=\"selected\" value=\"yes\">Yes, I want someone to make legal or financial decisions for me if I am unable to.</option>\n";
    }
    else {
      echo "<option value=\"yes\">Yes, I want someone to make legal or financial decisions for me if I am unable to.</option>\n";
    }
    if ($fp=="no") {
      echo "<option selected=\"selected\" value=\"no\">No, I do not want someone to make legal or financial decisions for me if I am unable to.</option>\n";
    }
    else {
      echo "<option value=\"no\">No, I do not want someone to make legal or financial decisions for me if I am unable to.</option>\n";
    }
    echo "</select>\n";
    echo "<br /><input class=\"btn\" type=\"submit\" name=\"group4\" value=\"Continue\" />\n";
    echo "</form>\n";
  }
}

if ($_SESSION["group"]=="5") {
  echo "<h2>Recommendations</h2><p>Based on your answers we recommend the following documents. We have made these documents available to you for free.</p>";
  if ($_SESSION["married"]=="married") {
    echo "<h3>Comprehensive Will for a Married Person</h3>\n";
    echo "<p>This enables you to:</p>\n";
    echo "<ul>\n";
    echo "  <li>make unlimited gifts in all sections of the will;</li>\n";
    echo "  <li>appoint guardians for any children you may have under the age of 18; and</li>\n";
    echo "  <li>leave money in trust for your partner or children.</li>\n";
    echo "</ul>\n";
  }
  else {
    echo "<h3>Comprehensive Will for an Unmarried Person</h3>\n";
    echo "<p>This enables you to:</p>\n";
    echo "<ul>\n";
    echo "  <li>make unlimited gifts in all sections of the will;</li>\n";
    echo "  <li>appoint guardians for any children you may have under the age of 18; and</li>\n";
    echo "  <li>leave money in trust for your partner or children.</li>\n";
    echo "</ul>\n";
  }
  if ($_SESSION["married"]=="engaged") {
    echo "<p><b>Note:</b> You answered that you are engaged. When you get married you should get a new will.</p>";
  }
  if ($_SESSION["children"]=="plan") {
    echo "<p><b>Note:</b> You answered that you are planning to have children. When you do have children you should get a new will.</p>";
  }
  if ($_SESSION["children"]=="undecided") {
    echo "<p><b>Note:</b> You answered that you are undecided whether you will have children. If you do have children you should get a new will.</p>";
  }
  if ($_SESSION["hc"]=="hc") {
    echo "<h3>Living Will and Healthcare Power of Attorney</h3>\n";
    echo "<p>Also known as an Advance Directive, this enables you to:</p>\n";
    echo "<ul>\n";
    echo "  <li>clarify your healthcare decisions so there's less worry for you and your family;</li>\n";
    echo "  <li>name someone to ensure that your wishes are followed and to make healthcare decisions for you if you can't.</li>\n";
    echo "</ul>\n";
  }
  if ($_SESSION["fp"]=="fp") {
    echo "<h3>Financial Power of Attorney </h3>\n";
    echo "<p>This enables you to choose someone you trust to handle your financial and legal affairs, should you become incapacitated.\n";
  }
  echo "<h2>Use our software to generate your estate planning documents for free:</h2>\n";
  echo "<form action=\"https://www.myimportantlegaldocs.com/vwc\" method=\"post\">\n";
  echo "<input type=\"hidden\" name=\"state\" value=\"".$_SESSION["state"]."\" />\n";
  echo "<input type=\"hidden\" name=\"married\" value=\"".$_SESSION["married"]."\" />\n";
  echo "<input type=\"submit\" class=\"btn\" value=\"Click to Start\" />\n";
  echo "</form>\n";
  echo "<h2>Find an attorney who provides pro bono services for veterans:</h2>\n";
  echo "<a class=\"btn\" href=\"http://www.vetsprobono.org/\">Click to Start</a>\n";
  echo "<h2>Find a lawyer in your state who provides fixed-fee online service:</h2>\n";
  echo "<a class=\"btn\" href=\"/online-lawyers/\">Click to Start</a>\n";
}

/*End of the Checkup*/

if ($_SESSION["group"]==""){

/*Show Introductory text if user has clicked Start*/

?>
<p>Do You Really Need an Estate Plan? Take our online checkup to determine which legal documents you need to protect yourself and your family. This is an anonymous checkup and conforms to our privacy guidelines. You don't have to register your email address and your personal data is not saved.</p>
<p>An estate plan contains the documents you need to ensure that your wishes regarding property, finances, and end-of-life care are granted. When you create an Estate Plan you get the following documents customized to your individual circumstances using our smart legal forms technology.</p>
<h2>Last Will</h2>
<p>A last will and testament lets you decide how you'd like to transfer your assets upon your death.</p>
<h2>Power of Attorney</h2>
<p>A power of attorney is an important part of an estate plan bundle which lets you choose someone who you trust to handle your financial and legal affairs, should you become incapacitated.</p>
<h2>Living Will/Healthcare Power of Attorney</h2>
<p>A living will helps you clarify your healthcare decisions so that there's less worry for you and your family. A living will provides direction to healthcare professionals about your end of life decisions and whether you wish to be resuscitated if you have a life-threatening condition. A Healthcare Power of Attorney allows you to name someone to ensure that your wishes are followed and to make healthcare decisions if you can't. Note that the Financial Power of Attorney document allows a chosen person to make financial and legal decisions for you should you become incapacitated, while a healthcare power of attorney allows a chosen person to follow through on your healthcare wishes should you be unable to.</p>
<a class="btn" href="/estate-planning-checkup/?checkup">Start Checkup</a>
<?php
}
?>